[package]
name = "dhcp_demo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"



[dependencies]
chrono = "0.4.41"
colored = "3.0.0"
